esircam_node:
  ros__parameters:
    stream_url: "http://esp32cam.local:81/stream"
#    stream_url: "http://localhost:8000/stream"
    frame_id: "camera_link"

    image_topic: "/camera/image_raw"
    compressed_topic: "/camera/compressed"

    reconnect_delay_sec: 2.0
    read_chunk_size: 1024
    log_every_n_frames: 30
